### ISSUE TITLE
Uncaught (in promise) Error: Unable to encode undefined of type undefined

### ISSUE THREAD

**Issue by dhavalwd** [prismicio/vuejs-starter#2]
## Issue
I am setting up a simple page as explained in the tutorial and I am getting this error. Let me know if I am missing something here. Below is the screenshot. 
<img width="1279" alt="screen shot 2018-08-13 at 1 31 40 pm" src="https://user-images.githubusercontent.com/7990968/44044868-46773946-9efd-11e8-971c-042362b2b52b.png">

## How to Reproduce?
Just follow all the steps mentioned in the tutorial.

**Comment by debiasio** [comment]
Hello @dhavalwd,

I have just followed the tutorial from the beginning, it works normally.

<img width="1680" alt="capture" src="https://user-images.githubusercontent.com/9430761/44212875-cfd23580-a16c-11e8-8bd0-c2e99b6505a3.png">

I don't guess what could be the problem. Can you publish your project code on a public GitHub repo, or send to me by email (jean-baptiste.de-biasio@prismic.io) the ZIP archive (without node_modules folder) of your project code.

**Comment by dhavalwd** [comment]
I have pushed my code to Github repo. [Link](https://github.com/dhavalwd/vuejs-prismic-test) for the repo.

I also see that you have updated this project for `Vue cli 3`. I cloned that new one and it works perfectly fine. I find this issue with older version.

**Comment by thibautdavoult** [comment]
I'm getting the same error message and this is the only place I've seen it associated with Prismic, so trying my luck in this issue!
I'm setting up a blog with Nuxt + Prismic. On index.vue I have:

```
asyncData () {
    const apiEndpoint = "https://thibautdavoult.prismic.io/api/v2"
    return Prismic.getApi(apiEndpoint).then((api) => {
      return api.getByUID('')
    }).then((response) => {
      return { articles: response  }
    })
}
```

When loading the page on local, this causes: "Unable to encode undefined of type undefined", and crashes my browser.

If I just change `api.getByUID('')` to `api.query('')`, then that works and all the documents get loaded into data:articles.
If you want to have a look at the repo: https://github.com/thibautdavoult/portfolio/tree/prismic
(branch prismic)

Like @dhavalwd, I'm thinking this may be a version issue. But still wanted to check if anyone had an idea.

Edit: So I just determined that querying by ID works. So there seems to be a problem with UID. I'd say more than likely on my end (first time with Nuxt & Prismic). I'll update if I make progress.

**Comment by levimykel** [comment]
Hi @dhavalwd and @thibautdavoult, sorry for the delay on this. I'll add it to our backlog and someone will look into this as soon as they are able. Thanks.

**Comment by TheDiehard22** [comment]
I have the very same problem in a nuxt.js 2.4.0 project when using the getByUID method.

Edit: This error is only generated when missing the 'custom-type' parameter. (https://prismic.io/docs/javascript/query-the-api/sdk-quick-query-helper-functions)
However, with the parameter - the method returns undefined.

**Comment by fchengpc** [comment]
having same issue, but even after i switching over to `api.query('')`, im still getting 
Error: Unable to encode undefined of type undefined but with `TypeError: Cannot read property 'cookie' of undefined`

But im using nextjs thou.

**Comment by zindlerb** [comment]
I experienced the same error recently. The reason the error was thrown for me was because the `api.getByUID` api is called with:
[`api.getByUID('<type>', '<uid>')`](https://prismic.io/docs/javascript/query-the-api/query-documents-by-id-or-uid)
not 
`api.getByUID('<uid>')`
This is a pretty generic error message so your error may be caused by something else.

**Comment by CareTiger** [comment]
I am getting the same error on the getByUID and the query.

**Comment by aaronransley** [comment]
@prismicio Running into this issue as well. Any word on a fix?

**Comment by MaximilianFranke** [comment]
I have the same Problem, some news?
![image](https://user-images.githubusercontent.com/10807500/130433963-70ab8370-21c6-49c2-824e-85764275c485.png)

**Comment by MarineLB** [comment]
I got the problem because my second argument in `getByUID` function call was `undefined`. using a string value fixed it!

**Comment by MaximilianFranke** [comment]
I use `getById` which dont accept a second String parameter and have this Problem.  With a other project the same code works and i see no difference

**Comment by dejardine** [comment]
I had this error, and it was because my template filed was _uid.vue (didn't work) _index.vue fixed it.

**Comment by Bergrebell** [comment]
had the same issue. using `const document = await $prismic.api.getByUID('home')` instead of `const document = await $prismic.api.getByUID('home')` did the trick for me.
